// HOME PRODUCTS TYPES
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'

// SHOP PRODUCTS TYPES
export const FETCH_SHOP_PRODUCTS_REQUEST = 'FETCH_SHOP_PRODUCTS_REQUEST'
export const FETCH_SHOP_PRODUCTS_SUCCESS = 'FETCH_SHOP_PRODUCTS_SUCCESS'
export const FETCH_SHOP_PRODUCTS_ERROR = 'FETCH_SHOP_PRODUCTS_ERROR'


// VENDOR PRODUCTS TYPES
export const FETCH_VENDOR_PRODUCTS_REQUEST = 'FETCH_VENDOR_PRODUCTS_REQUEST'
export const FETCH_VENDOR_PRODUCTS_SUCCESS = 'FETCH_VENDOR_PRODUCTS_SUCCESS'
export const FETCH_VENDOR_PRODUCTS_ERROR = 'FETCH_VENDOR_PRODUCTS_ERROR'

// VENDOR PRODUCTS TYPES
export const FETCH_SHOP_LIST_REQUEST = 'FETCH_SHOP_LIST_REQUEST'
export const FETCH_SHOP_LIST_SUCCESS = 'FETCH_SHOP_LIST_SUCCESS'
export const FETCH_SHOP_LIST_ERROR = 'FETCH_SHOP_LIST_ERROR'

// CATEGORY FETCH TYPES
export const FETCH_CATEGORIES = 'FETCH_SHOP_LIST_REQUEST'
