// HOME PRODUCTS TYPES
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'

// SHOP PRODUCTS TYPES
export const FETCH_SHOP_PRODUCTS_REQUEST = 'FETCH_SHOP_PRODUCTS_REQUEST'
export const FETCH_SHOP_PRODUCTS_SUCCESS = 'FETCH_SHOP_PRODUCTS_SUCCESS'
export const FETCH_SHOP_PRODUCTS_ERROR = 'FETCH_SHOP_PRODUCTS_ERROR'

// SHOP PRODUCT DETAILS TYPES
export const FETCH_PRODUCT_DETAILS_REQUEST = 'FETCH_PRODUCT_DETAILS_REQUEST'
export const FETCH_PRODUCT_DETAILS_SUCCESS = 'FETCH_PRODUCT_DETAILS_SUCCESS'
export const FETCH_PRODUCT_DETAILS_ERROR = 'FETCH_PRODUCT_DETAILS_ERROR'

// VENDOR PRODUCTS TYPES
export const FETCH_VENDOR_PRODUCTS_SUCCESS = 'FETCH_VENDOR_PRODUCTS_SUCCESS'
export const FETCH_VENDOR_PRODUCTS_REQUEST = 'FETCH_VENDOR_PRODUCTS_REQUEST'
export const FETCH_VENDOR_PRODUCTS_ERROR = 'FETCH_VENDOR_PRODUCTS_ERROR'

// VENDOR DETAILS TYPES
export const FETCH_VENDOR_DETAILS_REQUEST = 'FETCH_VENDOR_DETAILS_REQUEST'
export const FETCH_VENDOR_DETAILS_SUCCESS = 'FETCH_VENDOR_DETAILS_SUCCESS'
export const FETCH_VENDOR_DETAILS_ERROR = 'FETCH_VENDOR_DETAILS_ERROR'

// SHOP LIST TYPES
export const FETCH_SHOP_LIST_REQUEST = 'FETCH_SHOP_LIST_REQUEST'
export const FETCH_SHOP_LIST_SUCCESS = 'FETCH_SHOP_LIST_SUCCESS'
export const FETCH_SHOP_LIST_ERROR = 'FETCH_SHOP_LIST_ERROR'


// CATEGORY FETCH TYPES
export const FETCH_CATEGORIES = 'FETCH_SHOP_LIST_REQUEST'
export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY'
export const GET_CHILD_CATEGORY = 'GET_CHILD_CATEGORY'

// FILTER PRODUCTS TYPES
export const FILTER_PRODUCTS_BY_SIZE= 'FILTER_PRODUCTS_BY_SIZE'
export const FILTER_PRODUCTS_BY_PRICE = 'FILTER_PRODUCTS_BY_PRICE'
export const SHOW_PRODUCTS_BY_NUMBER = 'SHOW_PRODUCTS_BY_NUMBER'

// ADD-REMOVE TO BASKET
export const ADD_TO_BASKET = 'ADD_TO_BASKET'
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET'

// ADD CART ANIMATION
export const PRODUCT_ADD_CLEAR = 'PRODUCT_ADD_CLEAR'
export const PRODUCT_ADD = 'PRODUCT_ADD'
export const PRODUCT_ADD_FINISH = 'PRODUCT_ADD_FINISH'

// ADD-REMOVE TO WISH LIST
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST'

// ADD-REMOVE TO COMPARE
export const ADD_TO_COMPARE = 'ADD_TO_COMPARE'
export const REMOVE_FROM_COMPARE = 'REMOVE_FROM_COMPARE'

// ADD-REMOVE TO COMPARE
export const SHOW_QUICK_DES = 'SHOW_QUICK_DES'
export const REMOVE_QUICK_DES = 'REMOVE_QUICK_DES'

// GET PRODUCT SUGGETIONS
export const GET_PRODUCT_SUGGETIONS = 'GET_PRODUCT_SUGGETIONS'
export const FAILED_PRODUCT_SUGGETIONS = 'FAILED_PRODUCT_SUGGETIONS'

// SIGN UP ACTION
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'

// SEARCH PRODUCTS ACTION
export const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST'
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS'
export const SEARCH_PRODUCTS_ERROR = 'SEARCH_PRODUCTS_ERROR'

// USERS ACTION
export const USER_ACTIVITY_SUCCESS= 'USER_ACTIVITY_SUCCESS'
export const  USER_ACTIVITY_ERROR = 'USER_ACTIVITY_ERROR'